#+TITLE: Installation et configuration d’Emacs sous Windows
#+AUTHOR:
# #+OPTIONS: toc:t num:t
# #+TOC: headlines 4
#+STARTUP: content indent


* Présentation
:PROPERTIES:
:CUSTOM_ID: presentation
:END:

* Emacs pour Windows
:PROPERTIES:
:CUSTOM_ID: emacs-pour-windows
:END:

- Installer Emacs sous Windows
- Répertoires et fichiers à copier
- Configurer la variable d’environnement HOME
- Ajouter HOME\bin au PATH
- Installer et configurer GnuPG (GPG)
- Créer et chiffrer un fichier .authinfo.gpg
- Mplayer

** Installer Emacs pour Windows
:PROPERTIES:
:CUSTOM_ID: installer-emacs-pour-windows
:END:

https://www.gnu.org/software/emacs/download.html

Vérifier l’installation dans cmd.exe / PowerShell :
#+BEGIN_SRC shell
emacs --version
#+END_SRC
Si la commande n’est pas reconnue, ajouter Emacs au PATH :
*** cmd.exe
#+BEGIN_SRC shell
setx PATH "%PATH%;C:\Program Files\Emacs\bin"
#+END_SRC
*** powershell
#+BEGIN_SRC powershell 
[Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";C:\Program Files\Emacs\bin", [EnvironmentVariableTarget]::User)
#+END_SRC
Redémarrer le terminal.
** Configurer Emacs
:PROPERTIES:
:CUSTOM_ID: configurer-emacs
:END:

*** Fichiers et répertoires à copier depuis le dépôt
- emacs.d/early-init.el
- emacs.d/init.el
- emacs.d/elisp/
- emacs.d/config/
- emacs.d/sons/
- emacs.d/images/ (optionnel)

#+BEGIN_EXAMPLE
HOME/
   ├── .authinfo.gpg
   ├── bin/
   ├── GNU/
   ├── .emacs.d/
          ├── early-init.el
          ├── init.el
          ├── config/
          ├── elisp/
          └── sons/
#+END_EXAMPLE
** Configurer la variable HOME
:PROPERTIES:
:CUSTOM_ID: configurer-home
:END:

Définir HOME vers votre dossier utilisateur (persistant).
**** cmd.exe
#+BEGIN_SRC shell
setx HOME "%USERPROFILE%"
#+END_SRC
Redémarrer le terminal.
Vérifier :
#+BEGIN_SRC shell
echo %HOME%
#+END_SRC
**** PowerShell
#+BEGIN_SRC powershell
[Environment]::SetEnvironmentVariable("HOME", $Env:USERPROFILE, "User")
#+END_SRC
Redémarrer le terminal.
Vérifier :
#+BEGIN_SRC powershell
echo $Env:HOME
#+END_SRC
*** Ajouter %HOME%\\bin au PATH
:PROPERTIES:
:CUSTOM_ID: ajouter-home-bin-au-path
:END:

Créer le dossier :
#+BEGIN_SRC shell
mkdir %HOME%\bin
#+END_SRC
**** cmd.exe
#+BEGIN_SRC shell
setx PATH "%PATH%;%HOME%\bin"
#+END_SRC
Redémarrer le terminal.
Test du PATH
#+BEGIN_SRC shell
echo %PATH%
#+END_SRC
**** PowerShell
#+BEGIN_SRC powershell
[Environment]::SetEnvironmentVariable("Path", $Env:Path + ";" + "$Env:HOME\bin", "User")
#+END_SRC
Redémarrer le terminal.
Test du PATH
#+BEGIN_SRC powershell
$env:PATH
#+END_SRC
** Installer GPG 
:PROPERTIES:
:CUSTOM_ID: installer-gpg
:END:

Télécharger Gpg4win : https://gpg4win.org/
Vérifier l’installation :
#+BEGIN_SRC shell
gpg --version
#+END_SRC
*** Générer une clé GPG
:PROPERTIES:
:CUSTOM_ID: generer-une-cle-gpg
:END:

#+BEGIN_SRC shell
gpg --full-generate-key
#+END_SRC
Recommandations :
- Type : RSA and RSA
- Taille : 4096 bits
- Phrase secrète forte
Lister les clés :
#+BEGIN_SRC shell
gpg --list-secret-keys
#+END_SRC
*** Créer et chiffrer .authinfo
:PROPERTIES:
:CUSTOM_ID: creer-et-chiffrer-authinfo
:END:

/(Pour Gmail : créer un mot de passe d’application sur accounts.google.com si nécessaire.)/

Créer le fichier : %HOME%\.authinfo
Exemple de contenu :
#+BEGIN_SRC 
machine smtp.gmail.com login utilisateur@gmail.com password motdepasse port 587
machine imap.gmail.com login utilisateur@gmail.com password motdepasse port 993
#+END_SRC
Chiffrer le fichier (remplacez votre@email.com par votre UID GPG) :
#+BEGIN_SRC shell
gpg -e -r votre@email.com .authinfo
#+END_SRC
Sécuriser .authinfo.gpp
#+BEGIN_SRC shell
chmod 600 .authinfo.gpg
#+END_SRC
Supprimer le fichier en clair :
#+BEGIN_SRC shell
del .authinfo
#+END_SRC

*Conserver uniquement : .authinfo.gpg*

** Installer mplayer
:PROPERTIES:
:CUSTOM_ID: installer-mplayer
:END:

- Télécharger le binaire mplayer pour Windows.
- Installer dans %USERPROFILE%\bin ou %HOME%\bin.
Ajouter au PATH si nécessaire :
*** CMD
#+BEGIN_SRC shell
setx PATH "%PATH%;%HOME%\bin"
#+END_SRC
Redémarrer le terminal.
*** PowerShell
#+BEGIN_SRC powershell
[Environment]::SetEnvironmentVariable("Path", $Env:Path + ";" + "$Env:HOME\bin", "User")
#+END_SRC
Redémarrer le terminal.

** 9. Fichiers à éditer
:PROPERTIES:
:CUSTOM_ID: fichiers-a-editer
:END:

#+BEGIN_EXAMPLE
- %HOME%/.authinfo
- %HOME%/.emacs.d/config/emms_config.el
- %HOME%/.emacs.d/config/gnus_conf.el
- %HOME%/.emacs.d/config/email.el
- %HOME%/.emacs.d/config/meteo.el (coordonnées GPS)
#+END_EXAMPLE
-- 
* Notes de sécurité
:PROPERTIES:
:CUSTOM_ID: notes-de-securite
:END:
#+BEGIN_EXAMPLE
Ne jamais committer :
- .authinfo
- .authinfo.gpg
- Clés privées GPG
- Clés ivy-youtube dans emms_config
- Les adresses mail dans gnus-conf.el et email.el

Ajouter au .gitignore :
- .authinfo
- gnus-conf.el
- email.el
- emms_config
#+END_EXAMPLE  
